name: dadjokes
services:
  # ---------- PostgreSQL Database ----------
  db:
    image: postgres:16-alpine
    container_name: dadjokes-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: /run/secrets/postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dadjokes" ]
      interval: 5s
      timeout: 5s
      retries: 5

# From https://docs.docker.com/guides/pgadmin/
  pgadmin: # extra info/changes from https://www.youtube.com/watch?v=qECVC6t_2mU 
    image: dpage/pgadmin4:9.14 # updated it because I looked at https://www.pgadmin.org/docs/pgadmin4/latest/release_notes.html
    container_name: dadjokes-pgadmin
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: demo@example.com
      PGADMIN_DEFAULT_PASSWORD: secret

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: 'False'

      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    restart: always

  # --- Redis used for Cache
  redis:
    image: redis:7-alpine
    container_name: dadjokes-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

  # ---------- Express API ----------
  api:
    build:
      context: ./api
      target: dev
    container_name: dadjokes-api
    ports:
      - "3000:3000"
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER_FILE: /run/secrets/postgres_user
      DB_PASSWORD_FILE: /run/secrets/postgres_password
      DB_NAME_FILE: /run/secrets/postgres_db
      REDIS_URL: redis://redis:6379 #REDIS_URL has to be the same as in redis.ts
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

    # watch stuff
    # command: ["node", "--watch", "/app/src/index.ts"]
    develop:
      watch:
        - path: ./api/src
          action: sync
          target: /app/src
        - path: ./api/package*.json
          action: rebuild
          target: /app/package*.json

  # ---------- React Frontend (served by nginx) ----------
  frontend:
    build: 
      context: ./frontend
      target: dev
    container_name: dadjokes-frontend
    ports:
      #- "8080:80"
      - "8080:5173"
    depends_on:
      - api
    restart: unless-stopped
    # watch stuff
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/index.html
          target: /app/index.html
          action: sync
        - path: ./frontend/nginx.conf
          target: /etc/nginx/conf.d/default.conf
          action: sync+restart
        - path: ./frontend/package*.json
          target: /app/package*.json
          action: rebuild

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_db:
    file: ./secrets/postgres_db.txt

# top level volume
volumes:
  pgdata:
  redisdata: